---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: blazemeter-demo
  namespace: default
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: blazemeter-demo
  targetCPUUtilizationPercentage: 20
